### ISSUE TITLE
thank you for code but i have error

### ISSUE THREAD

**Issue by patrickwilson111** [AndroidSoftClub/QuoteApp#1]
friend when you press my quotes
Get a crash in the app 
There is a problem displaying quotes
can fix this ?

**Comment by patrickwilson111** [comment]
```
2022-04-18 03:03:35.572 841-3758/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: No permission to access APN settings
        at com.android.providers.telephony.TelephonyProvider.checkPermission(TelephonyProvider.java:3947)
        at com.android.providers.telephony.TelephonyProvider.checkPermissionCompat(TelephonyProvider.java:3964)
        at com.android.providers.telephony.TelephonyProvider.query(TelephonyProvider.java:2927)
        at android.content.ContentProvider.query(ContentProvider.java:1379)
        at android.content.ContentProvider.query(ContentProvider.java:1475)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:278)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
        at android.os.Binder.execTransact(Binder.java:1123)
2022-04-18 03:03:37.664 456-456/? E/netmgr: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:network' service: Invalid argument
2022-04-18 03:03:37.664 456-456/? E/netmgr: Failed to open QEMU pipe 'qemud:network': Invalid argument
2022-04-18 03:03:38.771 518-534/? E/RemoteAugmentedAutofillService: Bad service name for flags 1048704: com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiAugmentedAutofillService
2022-04-18 03:03:41.024 518-534/? E/RemoteAugmentedAutofillService: Bad service name for flags 1048704: com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiAugmentedAutofillService
2022-04-18 03:03:43.681 464-464/? E/wifi_forwarder: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:wififorward' service: Invalid argument
2022-04-18 03:03:43.681 464-464/? E/wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe
2022-04-18 03:03:44.151 518-534/? E/RemoteAugmentedAutofillService: Bad service name for flags 1048704: com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiAugmentedAutofillService
2022-04-18 03:03:52.674 30139-30139/? E/RecyclerView: No adapter attached; skipping layout
2022-04-18 03:03:52.674 30139-30139/? E/RecyclerView: No adapter attached; skipping layout
2022-04-18 03:03:52.697 30139-30463/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.Error: Error copying database
        at com.kessi.quotey.textquotes.qdatabase.DBHelper_dbfile.createDatabase(DBHelper_dbfile.java:58)
        at com.kessi.quotey.textquotes.fragment.TQuotesFrag$getTextQuotesAsync.doInBackground(TQuotesFrag.java:80)
        at com.kessi.quotey.textquotes.fragment.TQuotesFrag$getTextQuotesAsync.doInBackground(TQuotesFrag.java:69)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2022-04-18 03:03:52.855 518-548/? E/KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state: open failed: ENOENT (No such file or directory)
2022-04-18 03:03:52.855 518-548/? E/KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu1/cpufreq/stats/time_in_state: open failed: ENOENT (No such file or directory)
2022-04-18 03:03:52.903 205-208/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup34: Permission denied
2022-04-18 03:03:52.908 205-208/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup35: Permission denied
2022-04-18 03:04:03.283 205-208/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup34: Permission denied
2022-04-18 03:04:03.286 205-208/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup35: Permission denied
2022-04-18 03:04:15.996 29272-29334/? E/PlayCommon: [8234] nmh.b: Failed to connect to server for server timestamp: java.net.UnknownHostException: Unable to resolve host "play.googleapis.com": No address associated with hostname
2022-04-18 03:04:15.997 29272-29334/? E/PlayCommon: [8234] nmh.b: Failed to connect to server for log upload.
```
